In [5]:
w = []
edges = []

In [6]:
import numpy as np

In [35]:
def get_min_weight_cover(w, edges):
    w = np.array(w)
    edges = np.array(edges)
    n = len(w)
    min_weight_cover = np.inf
    best_covers = []

    for i in range(2**n):
        i_copy = i
        is_taken = []
        for j in range(n):
            is_taken.append(i_copy % 2 == 1)
            i_copy //= 2
        is_taken = np.array(is_taken)
        is_vertex_cover = True
        for e in edges:
            if not is_taken[e[0]] and not is_taken[e[1]]:
                is_vertex_cover = False
        if is_vertex_cover:
            weight_cover = np.sum(w[is_taken])
            if (weight_cover < min_weight_cover):
                min_weight_cover = weight_cover
                best_covers = [is_taken.nonzero()]
            elif weight_cover == min_weight_cover:
                best_covers.append(is_taken.nonzero())
    return min_weight_cover, best_covers

In [36]:
get_min_weight_cover([4, 1, 2, 3, 2, 2], 
                     [(0, 1), (0, 2), (0, 3), (0, 4), (2, 3), (3, 5), (4, 5)])

(8, [(array([1, 2, 3, 4]),), (array([0, 2, 5]),)])

In [37]:
get_min_weight_cover([2, 2, 3, 4, 4, 2, 2, 3, 2], 
                     [(0, 1), (1, 2), (2, 3), (2, 4), (4, 5), (5, 6), (4, 6), 
                     (3, 4), (3, 8), (3, 7), (7, 8), (7, 0)])

(15,
 [(array([1, 3, 4, 5, 7]),),
  (array([1, 3, 4, 6, 7]),),
  (array([0, 2, 3, 5, 6, 8]),)])

In [38]:
get_min_weight_cover([6, 3, 3, 3, 3, 3, 3], 
                     [(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 6), 
                     (1, 2), (2, 3), (3, 4), (4, 5), (5, 6)])

(15, [(array([0, 1, 3, 5]),), (array([0, 2, 4, 6]),)])

In [39]:
get_min_weight_cover([7, 3, 3, 3, 3, 3, 3, 3], 
                     [(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 7), (7, 6), 
                     (1, 2), (2, 3), (3, 4), (4, 5), (5, 6)])

(19,
 [(array([0, 1, 2, 4, 6]),),
  (array([0, 1, 3, 4, 6]),),
  (array([0, 1, 3, 5, 6]),),
  (array([0, 1, 3, 5, 7]),),
  (array([0, 2, 3, 5, 7]),),
  (array([0, 2, 4, 5, 7]),),
  (array([0, 2, 4, 6, 7]),)])